### ISSUE TITLE
User authentication libraries being deprecated. 

### ISSUE THREAD

**Issue by ALires** [bootdotdev/webapp#233]
Getting a warning in the console about libraries we use potentially being deprecated soon. There's a link for migration instructions.

Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.

**Comment by wagslane** [comment]
https://www.reddit.com/r/vuejs/comments/vzhjkk/a_vue3_google_signin_plugin/
