### ISSUE TITLE
Achievemet/Rank/Course Completion Modals should link to Discord

### ISSUE THREAD

**Issue by ALires** [bootdotdev/webapp#323]
We should link back to the discord with a simple message informing them that their achievement/rankup/Completed course was shared on discord

I think we could potentially go back to reporting all the progress stuff on discord regardless of if they have synced or not. Just have it use their first name.

Or we could just have a check that determines if someone is
1. Private - No message
2. Unsynced - Call to action to sync
Else
3. Link to the discord.

**Comment by wagslane** [comment]
> was shared on discord

How will we share it on discord if they haven't synced though? I think we need to address that in the ticket description.

**Comment by ALires** [comment]
@wagslane Updated with my thoughts
