### ISSUE TITLE
Exercise Nav Drop down cut off

### ISSUE THREAD

**Issue by ALires** [bootdotdev/webapp#324]
Depending on the chapter or exercise that is selected the drop down options width is set to the width of whatever is the main placeholder. 

If the selected option is a small Chapter heading, or small exercise heading - the dropdown options below it will be cut off. 

Example:
![image](https://user-images.githubusercontent.com/32534293/180890626-8d49151f-3772-41aa-93f4-a9d967cad8a8.png)

**Comment by wagslane** [comment]
Let's set a reasonable width, and then cut off the text with an ellipses
